urls:
  auth_host:        http://localhost:8002
  auth_login_path:  /api/v1/login
  auth_user_info_path:  /api/v1/user_info

adapter_urls:
  github:           http://localhost:8003
  vultr:            http://localhost:8004
  learn:            http://localhost:8006 
