source 'https://ruby.taobao.org'

gem 'sinatra'
gem 'activerecord'
gem 'standalone_migrations'
gem 'foreigner'
gem 'sqlite3'
gem 'rack-oauth2'
gem 'redis'
gem 'redis-namespace'
gem 'sidekiq'
gem 'http'
gem 'sinatra-cross_origin'
